apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sproozi
    app.kubernetes.io/managed-by: kustomize
  name: egress-gateway-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - sproozi.com
  resources:
  - agentruns
  - agentpolicies
  - agenttemplates
  verbs:
  - get
  - list
  - watch
