//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicy) DeepCopyInto(out *AgentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicy.
func (in *AgentPolicy) DeepCopy() *AgentPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyList) DeepCopyInto(out *AgentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyList.
func (in *AgentPolicyList) DeepCopy() *AgentPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyReference) DeepCopyInto(out *AgentPolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyReference.
func (in *AgentPolicyReference) DeepCopy() *AgentPolicyReference {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicySpec) DeepCopyInto(out *AgentPolicySpec) {
	*out = *in
	if in.AllowedCapabilities != nil {
		in, out := &in.AllowedCapabilities, &out.AllowedCapabilities
		*out = make([]CapabilityKind, len(*in))
		copy(*out, *in)
	}
	in.KubernetesRead.DeepCopyInto(&out.KubernetesRead)
	in.GitHubPullRequest.DeepCopyInto(&out.GitHubPullRequest)
	in.PackagesInstall.DeepCopyInto(&out.PackagesInstall)
	if in.EgressProfiles != nil {
		in, out := &in.EgressProfiles, &out.EgressProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budgets != nil {
		in, out := &in.Budgets, &out.Budgets
		*out = make(map[CapabilityKind]EndpointBudget, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ResourceBounds.DeepCopyInto(&out.ResourceBounds)
	out.MaxExecutionDuration = in.MaxExecutionDuration
	out.RetentionTTL = in.RetentionTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicySpec.
func (in *AgentPolicySpec) DeepCopy() *AgentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyStatus) DeepCopyInto(out *AgentPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyStatus.
func (in *AgentPolicyStatus) DeepCopy() *AgentPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRun) DeepCopyInto(out *AgentRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRun.
func (in *AgentRun) DeepCopy() *AgentRun {
	if in == nil {
		return nil
	}
	out := new(AgentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunIdentity) DeepCopyInto(out *AgentRunIdentity) {
	*out = *in
	if in.GrantedNamespaces != nil {
		in, out := &in.GrantedNamespaces, &out.GrantedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunIdentity.
func (in *AgentRunIdentity) DeepCopy() *AgentRunIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentRunIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunList) DeepCopyInto(out *AgentRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunList.
func (in *AgentRunList) DeepCopy() *AgentRunList {
	if in == nil {
		return nil
	}
	out := new(AgentRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSpec) DeepCopyInto(out *AgentRunSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.EventContext != nil {
		in, out := &in.EventContext, &out.EventContext
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]CapabilityKind, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSpec.
func (in *AgentRunSpec) DeepCopy() *AgentRunSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunStatus) DeepCopyInto(out *AgentRunStatus) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunStatus.
func (in *AgentRunStatus) DeepCopy() *AgentRunStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime) DeepCopyInto(out *AgentRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime.
func (in *AgentRuntime) DeepCopy() *AgentRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeList) DeepCopyInto(out *AgentRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeList.
func (in *AgentRuntimeList) DeepCopy() *AgentRuntimeList {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeReference) DeepCopyInto(out *AgentRuntimeReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeReference.
func (in *AgentRuntimeReference) DeepCopy() *AgentRuntimeReference {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeSpec) DeepCopyInto(out *AgentRuntimeSpec) {
	*out = *in
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	if in.WorkloadContainers != nil {
		in, out := &in.WorkloadContainers, &out.WorkloadContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ClientConfig = in.ClientConfig
	in.EphemeralWorkspace.DeepCopyInto(&out.EphemeralWorkspace)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeSpec.
func (in *AgentRuntimeSpec) DeepCopy() *AgentRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeStatus) DeepCopyInto(out *AgentRuntimeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeStatus.
func (in *AgentRuntimeStatus) DeepCopy() *AgentRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplate) DeepCopyInto(out *AgentTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplate.
func (in *AgentTemplate) DeepCopy() *AgentTemplate {
	if in == nil {
		return nil
	}
	out := new(AgentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateList) DeepCopyInto(out *AgentTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateList.
func (in *AgentTemplateList) DeepCopy() *AgentTemplateList {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateReference) DeepCopyInto(out *AgentTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateReference.
func (in *AgentTemplateReference) DeepCopy() *AgentTemplateReference {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateSpec) DeepCopyInto(out *AgentTemplateSpec) {
	*out = *in
	out.RuntimeRef = in.RuntimeRef
	out.PolicyRef = in.PolicyRef
	if in.EgressProfiles != nil {
		in, out := &in.EgressProfiles, &out.EgressProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateSpec.
func (in *AgentTemplateSpec) DeepCopy() *AgentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateStatus) DeepCopyInto(out *AgentTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateStatus.
func (in *AgentTemplateStatus) DeepCopy() *AgentTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointBudget) DeepCopyInto(out *EndpointBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointBudget.
func (in *EndpointBudget) DeepCopy() *EndpointBudget {
	if in == nil {
		return nil
	}
	out := new(EndpointBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralWorkspaceSpec) DeepCopyInto(out *EphemeralWorkspaceSpec) {
	*out = *in
	out.SizeLimit = in.SizeLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralWorkspaceSpec.
func (in *EphemeralWorkspaceSpec) DeepCopy() *EphemeralWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubPullRequestScope) DeepCopyInto(out *GitHubPullRequestScope) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedBaseBranches != nil {
		in, out := &in.AllowedBaseBranches, &out.AllowedBaseBranches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubPullRequestScope.
func (in *GitHubPullRequestScope) DeepCopy() *GitHubPullRequestScope {
	if in == nil {
		return nil
	}
	out := new(GitHubPullRequestScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesReadScope) DeepCopyInto(out *KubernetesReadScope) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]KubernetesReadResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesReadScope.
func (in *KubernetesReadScope) DeepCopy() *KubernetesReadScope {
	if in == nil {
		return nil
	}
	out := new(KubernetesReadScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageArtifact) DeepCopyInto(out *PackageArtifact) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]PackageDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageArtifact.
func (in *PackageArtifact) DeepCopy() *PackageArtifact {
	if in == nil {
		return nil
	}
	out := new(PackageArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageDependency) DeepCopyInto(out *PackageDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageDependency.
func (in *PackageDependency) DeepCopy() *PackageDependency {
	if in == nil {
		return nil
	}
	out := new(PackageDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackagesInstallScope) DeepCopyInto(out *PackagesInstallScope) {
	*out = *in
	if in.Ecosystems != nil {
		in, out := &in.Ecosystems, &out.Ecosystems
		*out = make([]PackageEcosystem, len(*in))
		copy(*out, *in)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]PackageArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackagesInstallScope.
func (in *PackagesInstallScope) DeepCopy() *PackagesInstallScope {
	if in == nil {
		return nil
	}
	out := new(PackagesInstallScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceBounds) DeepCopyInto(out *ResourceBounds) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceBounds.
func (in *ResourceBounds) DeepCopy() *ResourceBounds {
	if in == nil {
		return nil
	}
	out := new(ResourceBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeClientConfig) DeepCopyInto(out *RuntimeClientConfig) {
	*out = *in
	out.TrustBundleConfigMap = in.TrustBundleConfigMap
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeClientConfig.
func (in *RuntimeClientConfig) DeepCopy() *RuntimeClientConfig {
	if in == nil {
		return nil
	}
	out := new(RuntimeClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeConfigMapKeyReference) DeepCopyInto(out *RuntimeConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeConfigMapKeyReference.
func (in *RuntimeConfigMapKeyReference) DeepCopy() *RuntimeConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(RuntimeConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}
