apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: sproozi
    app.kubernetes.io/managed-by: kustomize
  name: allow-agent-traffic
  namespace: system
spec:
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - shared-gateway
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: sproozi-agents
    ports:
    - port: 8443
      protocol: TCP
